[project]
name = "lidar-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "numpy<2",
    "nuscenes-devkit>=1.1.11",
    "torch>=2.7.0",
]
